// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MinecraftProfile } from "./MinecraftProfile";

/**
 * What the frontend gets to see of the active session.
 */
export type AccountSession = { profile: MinecraftProfile, 
/**
 * The session couldn't be verified online (no network at startup):
 * singleplayer works, multiplayer servers will refuse it.
 */
offline: boolean, };
