// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * "Doesn't work with these versions of `id`".
 */
export type BreakRule = { id: string, 
/**
 * Versions concerned: a Maven range (Forge / NeoForge, e.g. `(,1.6.2)`)
 * or npm-style predicates joined by `||` (Fabric / Quilt, e.g. `<0.5`).
 * `None` = every version.
 */
versions: string | null, 
/**
 * Whether [`Self::versions`] is a Maven range.
 */
maven: boolean, };
