// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentHit = { project_id: string, slug: string, title: string, description: string, author: string, icon_url: string | null, downloads: number, project_type: string, };
