// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteProvider } from "./RemoteProvider";

/**
 * A catalogue project, whichever provider it comes from.
 */
export type ContentHit = { provider: RemoteProvider, project_id: string, slug: string, title: string, description: string, author: string, icon_url: string | null, downloads: number, 
/**
 * Project page on the provider's website.
 */
url: string, };
