// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much content an instance holds — counts only, nothing read or hashed.
 */
export type ContentSummary = { mods: number, mods_enabled: number, resource_packs: number, shaders: number, worlds: number, };
