// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CrashAnalysis = { summary: string, suggestion: string | null, matched_pattern: string, 
/**
 * Path of the crash report Minecraft wrote, when it logged one.
 */
crash_report: string | null, };
