// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceCodeInfo = { message: string | null, device_code: string, user_code: string, verification_uri: string, expires_in: number, interval: number, };
