// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadProgress = { task_id: string, label: string, bytes_done: number, bytes_total: number, files_done: number, files_total: number, };
