// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalSource } from "./ExternalSource";
import type { LoaderKind } from "./LoaderKind";

export type ExternalInstance = { 
/**
 * `<source>:<game dir>` — stable, and what [`import`] takes.
 */
id: string, source: ExternalSource, name: string, minecraft_version: string, loader: LoaderKind, loader_version: string | null, game_dir: string, mods: number, worlds: number, 
/**
 * Unix seconds.
 */
last_played: number | null, 
/**
 * An instance was already imported from it.
 */
already_imported: boolean, };
