// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One exact Modrinth version added to a server's modpack. Only its own file
 * is installed: the pack already ships what it depends on.
 */
export type ExtraMod = { 
/**
 * Modrinth slug, for messages.
 */
project: string, version_id: string, };
