// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerModpack } from "./ServerModpack";

export type FeaturedServer = { id: string, name: string, address: string, description: string, tags: Array<string>, language: string, minecraft_version: string, website: string | null, 
/**
 * Mods the server itself needs (e.g. a voice chat), always installed.
 */
required_mods: Array<string>, 
/**
 * Modded servers: the exact modpack version to install instead of the
 * Fabric presets.
 */
modpack: ServerModpack | null, };
