// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloseBehavior } from "./CloseBehavior";
import type { JvmPreset } from "./JvmPreset";
import type { LauncherBehavior } from "./LauncherBehavior";

export type GlobalSettings = { default_min_memory_mb: number, default_max_memory_mb: number, default_jvm_args: Array<string>, 
/**
 * Public-client Azure AD application id (device code flow, `consumers`
 * tenant). Defaults to Largy Launcher's own — see [`DEFAULT_AZURE_CLIENT_ID`].
 */
azure_client_id: string, 
/**
 * CurseForge Core API key from console.curseforge.com — required to
 * browse/install CurseForge modpacks.
 */
curseforge_api_key: string, java_path_override: string | null, 
/**
 * Bypasses the Microsoft login requirement at launch, using a local
 * name-only profile instead (see `auth::offline_session`). Only usable
 * on singleplayer or servers explicitly running in offline mode — real
 * online-mode servers reject it.
 */
offline_mode: boolean, offline_username: string, 
/**
 * What the launcher window does once a game is running.
 */
on_game_launch: LauncherBehavior, 
/**
 * What closing the window does. Reducing to the tray keeps play-time
 * tracking and crash reports working for games still running.
 */
on_close: CloseBehavior, 
/**
 * Shows the instance being played on the player's Discord profile.
 */
discord_rich_presence: boolean, 
/**
 * Named memory/JVM combinations the player saved from an instance's
 * settings, reusable across any other instance.
 */
jvm_presets: Array<JvmPreset>, };
