// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrashAnalysis } from "./CrashAnalysis";

export type InstanceExit = { instance_id: string, code: number | null, crash_analysis: CrashAnalysis | null, 
/**
 * Stopped from the launcher — a non-zero code is expected, not a crash.
 */
killed: boolean, };
