// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file that didn't make it into the instance automatically — kept
 * structured so the frontend can offer real actions (open the download
 * page, open the folder).
 */
export type InstallWarning = { file_name: string, message: string, browser_url: string | null, 
/**
 * Instance-relative destination of a file the player has to download
 * by hand — lets the launcher pick it up from their Downloads folder.
 */
path: string | null, sha1: string | null, };
