// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallWarning } from "./InstallWarning";
import type { Instance } from "./Instance";

/**
 * Result of an instance install/update: the instance itself, plus any
 * per-file problems that didn't stop the install but left it incomplete.
 */
export type InstanceInstallResult = { instance: Instance, warnings: Array<InstallWarning>, };
