// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakRule } from "./BreakRule";
import type { RemoteProject } from "./RemoteProject";

/**
 * One installed mod, resource pack or shader pack.
 */
export type InstalledItem = { 
/**
 * File name without the `.disabled` suffix.
 */
file_name: string, enabled: boolean, 
/**
 * An unpacked pack (folder) rather than a file — can't be disabled.
 */
is_dir: boolean, size: number, 
/**
 * Unix seconds.
 */
modified: number, sha1: string | null, 
/**
 * CurseForge fingerprint, to compare with a project's files.
 */
fingerprint: number | null, mod_id: string | null, name: string | null, version: string | null, description: string | null, authors: Array<string>, loaders: Array<string>, 
/**
 * For the instance's loader: mod ids this file provides, requires, and
 * declares itself incompatible with.
 */
provides: Array<string>, depends: Array<string>, breaks: Array<BreakRule>, 
/**
 * Absolute path of the extracted icon (served by the asset protocol).
 */
icon_path: string | null, remote: RemoteProject | null, };
