// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderKind } from "./LoaderKind";
import type { ModpackRef } from "./ModpackRef";
import type { PlaySession } from "./PlaySession";

export type Instance = { id: string, name: string, minecraft_version: string, loader: LoaderKind, loader_version: string | null, directory: string, icon_url: string | null, min_memory_mb: number | null, max_memory_mb: number | null, extra_jvm_args: Array<string>, modpack: ModpackRef | null, created_at: number, last_played_at: number | null, 
/**
 * Cumulative time spent in-game across every session, in seconds.
 */
play_time_seconds: number, 
/**
 * Java executable for this instance only; falls back to the global
 * override, then to the Mojang-managed runtime.
 */
java_path: string | null, window_width: number | null, window_height: number | null, fullscreen: boolean, 
/**
 * `host[:port]` to join straight from the main menu.
 */
auto_join_server: string | null, 
/**
 * Catalog server (see `servers::featured`) this instance was prepared for.
 */
featured_server: string | null, 
/**
 * Kept above the fold in every sort order in the instance list.
 */
pinned: boolean, 
/**
 * Blocks [`delete`] until explicitly turned off — a safety net for
 * instances the player doesn't want to lose to a stray click.
 */
protected: boolean, 
/**
 * Free-form notes the player writes for themselves.
 */
notes: string, 
/**
 * Most recent play sessions, newest first, capped to [`MAX_SESSIONS`].
 */
sessions: Array<PlaySession>, 
/**
 * [`external::ExternalInstance::id`] this instance was imported from.
 */
imported_from: string | null, };
