// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceSettingsInput = { min_memory_mb: number | null, max_memory_mb: number | null, extra_jvm_args: Array<string>, java_path: string | null, window_width: number | null, window_height: number | null, fullscreen: boolean, auto_join_server: string | null, };
