// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLine } from "./LogLine";

export type InstanceLogBatch = { instance_id: string, lines: Array<LogLine>, };
