// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JavaInstallation = { path: string, version: string, major: number, 
/**
 * `managed` (downloaded by the launcher) or `system`.
 */
source: string, };
