// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reusable, user-named memory/JVM combination — distinct from the fixed
 * one-click optimizations in `lib/jvmPresets.ts` on the frontend.
 */
export type JvmPreset = { name: string, min_memory_mb: number, max_memory_mb: number, extra_jvm_args: Array<string>, };
