// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkinVariant } from "./SkinVariant";

/**
 * A library entry with its texture, for the UI.
 */
export type LibrarySkin = { texture: string, id: string, name: string, variant: SkinVariant, added_at: number, };
