// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManualFile = { 
/**
 * Instance-relative destination, e.g. `mods/foo-1.2.jar`.
 */
path: string, sha1: string | null, };
