// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderKind } from "./LoaderKind";

export type ModpackVersionSummary = { id: string, name: string, minecraft_version: string, loader: LoaderKind, loader_version: string, };
