// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderKind } from "./LoaderKind";

export type ModpackSummary = { id: string, provider: string, name: string, author: string, icon_url: string | null, summary: string, downloads: number | null, 
/**
 * Newest Minecraft release versions the pack supports, newest first.
 */
game_versions: Array<string>, loaders: Array<LoaderKind>, 
/**
 * Unix seconds of the pack's last update.
 */
updated_at: number | null, };
