// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModpackRef = { provider: string, pack_id: string, version_id: string, pack_name: string, 
/**
 * Paths (relative to the instance directory) of every file this
 * modpack version placed on disk — downloaded mod files and any
 * `overrides/` files alike. Used by `instances_update_modpack` to know
 * which files a newer version no longer ships and can safely remove;
 * anything not in this list (saves, manual additions) is never touched.
 * `#[serde(default)]` so instances installed before this field existed
 * just have an empty list (no retroactive pruning on their first update).
 */
installed_files: Array<string>, };
