// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModpackSummary = { id: string, provider: string, name: string, author: string, icon_url: string | null, summary: string, downloads: number | null, };
