// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModpackSummary } from "./ModpackSummary";

export type ModpackDetails = { summary: ModpackSummary, description: string, };
