// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModUpdate = { file_name: string, project_id: string, title: string, icon_url: string | null, current_version: string, new_version: string, new_file_name: string, url: string, sha1: string, size: number, };
