// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptimizeStatus } from "./OptimizeStatus";

export type OptimizeItem = { 
/**
 * Modrinth slug to install (the first candidate when none fits).
 */
slug: string, title: string, reason: string, icon_url: string | null, status: OptimizeStatus, 
/**
 * The installed mod that already covers it, for `Present`.
 */
covered_by: string | null, };
