// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A catalogue category modpacks can be filtered by.
 */
export type PackCategory = { id: string, label: string, };
