// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One completed play session, recorded when the game process exits.
 */
export type PlaySession = { started_at: number, duration_seconds: number, };
