// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrepareSpec = { 
/**
 * Catalog id, or `None` for a server the player typed in.
 */
featured_id: string | null, name: string, address: string, minecraft_version: string, mods: Array<string>, shaders: Array<string>, 
/**
 * `data:image/png;base64,...` favicon from the server's ping.
 */
icon: string | null, };
