// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Instance } from "./Instance";

export type PrepareResult = { instance: Instance, 
/**
 * Mods or shaders that couldn't be installed (the instance still works).
 */
warnings: Array<string>, };
