// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteProvider } from "./RemoteProvider";

/**
 * The catalogue project an installed file comes from.
 */
export type RemoteProject = { provider: RemoteProvider, project_id: string, title: string, description: string, icon_url: string | null, 
/**
 * Project page on the provider's website.
 */
url: string, };
