// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Screenshot = { file_name: string, 
/**
 * Absolute path, turned into an asset URL by the frontend.
 */
path: string, size: number, 
/**
 * Unix seconds (file modification time).
 */
taken_at: number, };
