// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderKind } from "./LoaderKind";
import type { SearchSort } from "./SearchSort";

export type SearchQuery = { text: string, offset: number, game_version: string | null, loader: LoaderKind | null, 
/**
 * A [`PackCategory::id`] of the same provider.
 */
category: string | null, sort: SearchSort, };
