// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtraMod } from "./ExtraMod";

export type ServerModpack = { 
/**
 * `ftb`, `modrinth` or `curseforge`.
 */
provider: "ftb" | "modrinth" | "curseforge", pack_id: string, version_id: string, name: string, 
/**
 * Version as the pack author names it (e.g. `1.18.1`).
 */
version_name: string, 
/**
 * Mods the server adds on top of the pack, installed after it.
 */
extra_mods: Array<ExtraMod>, };
