// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerEntry = { name: string, address: string, 
/**
 * Base64 PNG the game cached from the server's last ping.
 */
icon: string | null, };
