// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerPreset = { id: string, label: string, description: string, default: boolean, 
/**
 * Modrinth project slugs (Fabric mods).
 */
mods: Array<string>, 
/**
 * Modrinth shader pack slugs; the first one is switched on.
 */
shaders: Array<string>, };
