// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeaturedServer } from "./FeaturedServer";
import type { ServerPreset } from "./ServerPreset";

export type ServerCatalog = { schema: number, presets: Array<ServerPreset>, servers: Array<FeaturedServer>, };
