// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerStatus = { online: number, max: number, version: string, 
/**
 * `§`-coded description, see [`super::motd`].
 */
motd: string, 
/**
 * `data:image/png;base64,...` as the server sends it.
 */
favicon: string | null, latency_ms: number, 
/**
 * Sample of connected player names (servers may hide or fake it).
 */
players: Array<string>, };
