// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cape } from "./Cape";
import type { SkinVariant } from "./SkinVariant";

export type SkinProfile = { name: string, variant: SkinVariant, 
/**
 * Data URL of the active skin; `None` for the default skin.
 */
skin: string | null, capes: Array<Cape>, };
