// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderKind } from "./LoaderKind";

export type Snapshot = { 
/**
 * Folder name — the snapshot's id.
 */
id: string, 
/**
 * Unix seconds.
 */
created_at: number, 
/**
 * Why it was taken, shown to the player ("Avant la mise à jour de 12 mods").
 */
reason: string, minecraft_version: string, loader: LoaderKind, loader_version: string | null, 
/**
 * Modpack version name/id at the time, if any.
 */
modpack_version: string | null, 
/**
 * Files in the snapshot (for the UI: "183 mods").
 */
mods: number, };
