// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VersionManifestEntry = { id: string, type: string, url: string, releaseTime: string, };
