// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type World = { 
/**
 * Folder name in `saves/` (the world's id for every other call).
 */
folder: string, 
/**
 * In-game name, falling back to the folder name.
 */
name: string, 
/**
 * `survival`, `creative`, `adventure` or `spectator`.
 */
game_mode: string | null, hardcore: boolean, cheats: boolean, 
/**
 * Unix seconds.
 */
last_played: number | null, version: string | null, size: number, 
/**
 * Absolute path of the world's `icon.png` (asset protocol).
 */
icon_path: string | null, };
