// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorldBackup = { 
/**
 * Path relative to the instance's backup folder — its id.
 */
id: string, 
/**
 * The world it holds, or `None` for a snapshot of every world.
 */
world: string | null, 
/**
 * Unix seconds.
 */
created_at: number, size: number, };
