//! Export an instance as a Modrinth `.mrpack`, importable by Largy, Prism,
//! the Modrinth App and most other launchers. Files Modrinth knows (matched
//! by SHA-1) are referenced by URL; everything else ships in `overrides/`.

use std::collections::HashMap;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};

use serde::Serialize;
use serde_json::json;
use sha1::Sha1;
use sha2::{Digest, Sha512};

use crate::error::{AppError, AppResult};
use crate::providers::modrinth::ModrinthApi;
use crate::providers::LoaderKind;

use super::backup::zip_dir;
use super::Instance;

/// Folders whose files may be replaced by Modrinth download references.
const CONTENT_DIRS: &[&str] = &["mods", "resourcepacks", "shaderpacks"];
/// Never exported: machine-specific or regenerated by the game/launcher.
const EXCLUDED: &[&str] = &[
    "natives",
    "logs",
    "crash-reports",
    "screenshots",
    "instance.json",
    ".largy-launch-args.txt",
    "usercache.json",
    "usernamecache.json",
    ".mixin.out",
    ".fabric",
    ".cache",
    "debug",
    "downloads",
];

#[derive(Debug, Serialize)]
pub struct ExportSummary {
    pub path: String,
    pub referenced: usize,
    pub bundled: usize,
}

struct HashedFile {
    rel: String,
    abs: PathBuf,
    sha1: String,
    sha512: String,
    size: u64,
}

fn hash_file(path: &Path) -> std::io::Result<(String, String, u64)> {
    let mut file = std::fs::File::open(path)?;
    let (mut s1, mut s512) = (Sha1::new(), Sha512::new());
    let mut buf = vec![0u8; 128 * 1024];
    let mut size = 0u64;
    loop {
        let n = file.read(&mut buf)?;
        if n == 0 {
            break;
        }
        s1.update(&buf[..n]);
        s512.update(&buf[..n]);
        size += n as u64;
    }
    Ok((hex::encode(s1.finalize()), hex::encode(s512.finalize()), size))
}

fn content_files(instance_dir: &Path) -> std::io::Result<Vec<HashedFile>> {
    let mut out = Vec::new();
    for dir in CONTENT_DIRS {
        let Ok(entries) = std::fs::read_dir(instance_dir.join(dir)) else {
            continue;
        };
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().into_owned();
            if !entry.file_type()?.is_file() || name.ends_with(".disabled") {
                continue;
            }
            let (sha1, sha512, size) = hash_file(&entry.path())?;
            out.push(HashedFile { rel: format!("{dir}/{name}"), abs: entry.path(), sha1, sha512, size });
        }
    }
    Ok(out)
}

fn loader_dependency(instance: &Instance) -> Option<(&'static str, String)> {
    let version = instance.loader_version.clone()?;
    match instance.loader {
        LoaderKind::Vanilla => None,
        LoaderKind::Fabric => Some(("fabric-loader", version)),
        LoaderKind::Quilt => Some(("quilt-loader", version)),
        LoaderKind::Forge => Some(("forge", version)),
        LoaderKind::NeoForge => {
            Some(("neoforge", version.strip_prefix("1.20.1-").map(str::to_string).unwrap_or(version)))
        }
    }
}

pub async fn export_mrpack(
    api: &ModrinthApi,
    instance: &Instance,
    dest: &Path,
    include_saves: bool,
) -> AppResult<ExportSummary> {
    let dir = instance.directory.clone();
    let files = tokio::task::spawn_blocking(move || content_files(&dir))
        .await
        .map_err(|e| AppError::Other(e.to_string()))??;

    let hashes: Vec<String> = files.iter().map(|f| f.sha1.clone()).collect();
    let known = match api.versions_by_hash(&hashes).await {
        Ok(known) => known,
        Err(e) => {
            tracing::warn!("modrinth lookup failed during export, bundling every file: {e}");
            HashMap::new()
        }
    };

    let mut index_files = Vec::new();
    let mut bundled: Vec<(String, PathBuf)> = Vec::new();
    for file in &files {
        let url = known.get(&file.sha1).and_then(|v| v.files.iter().find(|f| f.hashes.sha1 == file.sha1)).map(|f| f.url.clone());
        match url {
            Some(url) => index_files.push(json!({
                "path": file.rel,
                "hashes": { "sha1": file.sha1, "sha512": file.sha512 },
                "env": { "client": "required", "server": "required" },
                "downloads": [url],
                "fileSize": file.size,
            })),
            None => bundled.push((file.rel.clone(), file.abs.clone())),
        }
    }

    let mut dependencies = serde_json::Map::new();
    dependencies.insert("minecraft".to_string(), json!(instance.minecraft_version));
    if let Some((key, version)) = loader_dependency(instance) {
        dependencies.insert(key.to_string(), json!(version));
    }
    let index = json!({
        "formatVersion": 1,
        "game": "minecraft",
        "versionId": chrono::Local::now().format("%Y.%m.%d").to_string(),
        "name": instance.name,
        "files": index_files,
        "dependencies": dependencies,
    });

    let referenced = index_files_len(&index);
    let bundled_count = bundled.len();
    let (instance_dir, dest_owned) = (instance.directory.clone(), dest.to_path_buf());
    tokio::task::spawn_blocking(move || write_mrpack(&dest_owned, &instance_dir, &index, &bundled, include_saves))
        .await
        .map_err(|e| AppError::Other(e.to_string()))??;

    Ok(ExportSummary { path: dest.display().to_string(), referenced, bundled: bundled_count })
}

fn index_files_len(index: &serde_json::Value) -> usize {
    index["files"].as_array().map_or(0, Vec::len)
}

fn write_mrpack(
    dest: &Path,
    instance_dir: &Path,
    index: &serde_json::Value,
    bundled: &[(String, PathBuf)],
    include_saves: bool,
) -> AppResult<()> {
    let tmp = dest.with_extension("mrpack.part");
    let result = (|| -> AppResult<()> {
        let mut zip = zip::ZipWriter::new(std::fs::File::create(&tmp)?);
        let options = zip::write::SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);
        zip.start_file("modrinth.index.json", options)?;
        zip.write_all(serde_json::to_string_pretty(index)?.as_bytes())?;

        for (rel, abs) in bundled {
            zip.start_file(format!("overrides/{rel}"), options)?;
            std::io::copy(&mut std::fs::File::open(abs)?, &mut zip)?;
        }

        for entry in std::fs::read_dir(instance_dir)? {
            let entry = entry?;
            let name = entry.file_name().to_string_lossy().into_owned();
            if EXCLUDED.contains(&name.as_str()) || CONTENT_DIRS.contains(&name.as_str()) || name.starts_with(".largy") {
                continue;
            }
            if name == "saves" && !include_saves {
                continue;
            }
            if entry.file_type()?.is_dir() {
                zip_dir(&mut zip, &entry.path(), &format!("overrides/{name}"))?;
            } else {
                zip.start_file(format!("overrides/{name}"), options)?;
                std::io::copy(&mut std::fs::File::open(entry.path())?, &mut zip)?;
            }
        }
        zip.finish()?;
        Ok(())
    })();
    if let Err(e) = result {
        let _ = std::fs::remove_file(&tmp);
        return Err(e);
    }
    std::fs::rename(&tmp, dest)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn written_pack_contains_index_overrides_and_skips_excluded_folders() {
        let root = tempfile::tempdir().unwrap();
        let inst = root.path().join("inst");
        for d in ["mods", "config", "logs", "saves/W"] {
            std::fs::create_dir_all(inst.join(d)).unwrap();
        }
        std::fs::write(inst.join("mods/custom.jar"), b"jar").unwrap();
        std::fs::write(inst.join("config/a.toml"), b"cfg").unwrap();
        std::fs::write(inst.join("logs/latest.log"), b"log").unwrap();
        std::fs::write(inst.join("saves/W/level.dat"), b"lvl").unwrap();
        std::fs::write(inst.join("options.txt"), b"opt").unwrap();

        let dest = root.path().join("out.mrpack");
        let index = json!({"formatVersion": 1, "files": [], "dependencies": {"minecraft": "1.20.1"}});
        let bundled = vec![("mods/custom.jar".to_string(), inst.join("mods/custom.jar"))];
        write_mrpack(&dest, &inst, &index, &bundled, false).unwrap();

        let mut archive = zip::ZipArchive::new(std::fs::File::open(&dest).unwrap()).unwrap();
        for present in ["modrinth.index.json", "overrides/mods/custom.jar", "overrides/config/a.toml", "overrides/options.txt"] {
            assert!(archive.by_name(present).is_ok(), "{present}");
        }
        for absent in ["overrides/logs/latest.log", "overrides/saves/W/level.dat"] {
            assert!(archive.by_name(absent).is_err(), "{absent}");
        }
    }

    #[test]
    fn neoforge_1_20_1_versions_are_exported_without_the_minecraft_prefix() {
        let mut instance: Instance = serde_json::from_value(json!({
            "id": "i", "name": "n", "minecraft_version": "1.20.1", "loader": "neoforge",
            "loader_version": "1.20.1-47.1.106", "directory": "/x"
        }))
        .unwrap();
        assert_eq!(loader_dependency(&instance), Some(("neoforge", "47.1.106".to_string())));
        instance.loader = LoaderKind::Vanilla;
        assert_eq!(loader_dependency(&instance), None);
    }
}
